COMMENT ON TABLE events IS 'Events represent real-world things that have happened.';
COMMENT ON column events.anchor_date is 'If present, it overrides eventDate as the base date used when calculating obligation deadlines.';

comment on table obligation_templates is 'Obligation templates define how obligations should be generated when an event occurs. 
e.g. If event X occurs then Create obligation Y which is Due Z days later.';

comment on table obligations is 'Obligations are the results (tasks) generated by the engine.';

comment on table recurrence_rules is 'Some obligations are not triggered by events. These are stored in recurrence_rules.';

comment on column recurrence_rules.start_date is 'The first point in time from which this rule begins generating events. i.e. When does this obligation stream begin?';
comment on column recurrence_rules.end_date is 'Stop generating events after this date';
